# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17a7a43ee8b660c9dfc65e829366f8f7fe626b5d838e8e6deeea913299380f358b567fa88a0e6697ccf11fa88d628c0440254a92e8a31e61f1a1c60110bd900

test:
  secret_key_base: b52e6ab7d73e023d105e9f4096f19ce4c2669e7aba57be2a12de39779f77f6aaf119da5946ab33b3291cd25117861309a37972e1675e687702a93688f21f9e22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
